
version: '3'

services:
  storefront-ui:
    build:
      context: .
      dockerfile: ui.dockerfile
    volumes:
      - ./nginx/data/nginx:/etc/nginx/conf.d
      - ./nginx/data/certbot/conf:/etc/letsencrypt
    network_mode: host
    environment:
      - MAPS_KEY=somekey
